export const PRODUCTS = [
  {
    id: 1,
    name: "Fresh Toned Milk",
    category: "Dairy & Eggs",
    unit: "500 ml",
    price: 32,
    mrp: 35,
    image:
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80",
    badge: "Daily Fresh",
    discount: "9% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 2,
    name: "Farm Fresh Eggs",
    category: "Dairy & Eggs",
    unit: "6 pcs",
    price: 36,
    mrp: 54,
    image:
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80",
    badge: "Farm Fresh",
    discount: "11% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 3,
    name: "Fresh Curd",
    category: "Dairy & Eggs",
    unit: "500 g",
    price: 60,
    mrp: 50,
    image: "/curd.jpg",
    badge: "Fresh",
    discount: "10% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 4,
    name: "Paneer",
    category: "Dairy & Eggs",
    unit: "200 g",
    price: 85,
    mrp: 95,
    image: "/paneer.jpg",
    badge: "Protein Rich",
    discount: "11% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 5,
    name: "Tomato",
    category: "Fruits & Vegetables",
    unit: "1 kg",
    price: 30,
    mrp: 36,
    image:
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80",
    badge: "Fresh Veg",
    discount: "17% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 6,
    name: "Onion",
    category: "Fruits & Vegetables",
    unit: "1 kg",
    price: 32,
    mrp: 38,
    image:
      "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=600&q=80",
    badge: "Kitchen Essential",
    discount: "16% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 7,
    name: "Potato",
    category: "Fruits & Vegetables",
    unit: "1 kg",
    price: 28,
    mrp: 34,
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80",
    badge: "Daily Need",
    discount: "18% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 8,
    name: "Green Chilli",
    category: "Fruits & Vegetables",
    unit: "250 g",
    price: 20,
    mrp: 25,
    image:
      "https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?auto=format&fit=crop&w=600&q=80",
    badge: "Fresh",
    discount: "20% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 9,
    name: "Glucose Biscuits",
    category: "Snacks & Biscuits",
    unit: "250 g",
    price: 25,
    mrp: 28,
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    badge: "Popular",
    discount: "11% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 10,
    name: "Cookies Pack",
    category: "Snacks & Biscuits",
    unit: "200 g",
    price: 35,
    mrp: 40,
    image: "/parlage.png",
    badge: "Snack Time",
    discount: "13% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 11,
    name: "Masala Chips",
    category: "Snacks & Biscuits",
    unit: "1 pack",
    price: 20,
    mrp: 20,
    image:
      "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=600&q=80",
    badge: "Crispy",
    discount: "Best Price",
    bestSeller: false,
    inStock: true,
    lowStock: true,
  },
  {
    id: 12,
    name: "Vanilla Ice Cream Cup",
    category: "Ice Creams",
    unit: "100 ml",
    price: 35,
    mrp: 40,
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80",
    badge: "Cold Treat",
    discount: "13% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 14,
    name: "Rice",
    category: "Atta, Rice & Dal",
    unit: "1 kg",
    price: 60,
    mrp: 65,
    image:
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
    badge: "Staple",
    discount: "8% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 15,
    name: "Wheat Atta",
    category: "Atta, Rice & Dal",
    unit: "1 kg",
    price: 42,
    mrp: 48,
    image:
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
    badge: "Daily Cooking",
    discount: "13% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 16,
    name: "Sugar",
    category: "Atta, Rice & Dal",
    unit: "1 kg",
    price: 45,
    mrp: 50,
    image: "/sugar.png",
    badge: "Essential",
    discount: "10% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 17,
    name: "Cooking Oil",
    category: "Grocery Essentials",
    unit: "1 litre",
    price: 145,
    mrp: 160,
    image: "/oil.png",
    badge: "Kitchen Must-Have",
    discount: "9% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 18,
    name: "Bath Soap",
    category: "Daily Needs",
    unit: "1 pc",
    price: 38,
    mrp: 42,
    image: "/soap.png",
    badge: "Home Care",
    discount: "10% OFF",
    bestSeller: false,
    inStock: true,
    lowStock: true,
  },
  {
    id: 19,
    name: "Toothpaste",
    category: "Daily Needs",
    unit: "100 g",
    price: 65,
    mrp: 72,
    image: "/paste.png",
    badge: "Morning Need",
    discount: "10% OFF",
    bestSeller: false,
    inStock: true,
  },
  {
    id: 21,
    name: "Mill Fresh Red Chilli Powder",
    category: "Mill Fresh Powders",
    unit: "1 kg",
    price: 350,
    mrp: 380,
    image: "/red-chilli-powder.png",
    badge: "Freshly Ground",
    discount: "8% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 22,
    name: "Mill Fresh Turmeric Powder",
    category: "Mill Fresh Powders",
    unit: "1 kg",
    price: 300,
    mrp: 330,
    image: "/turmeric-powder.png",
    badge: "Natural Haldi",
    discount: "9% OFF",
    bestSeller: true,
    inStock: true,
  },
  {
    id: 23,
    name: "Rice Flour",
    category: "Mill Fresh Powders",
    unit: "1 kg",
    price: 30,
    mrp: 35,
    image: "/rice-flour.png",
    badge: "Freshly Milled",
    discount: "14% OFF",
    bestSeller: false,
    inStock: true,
  },
];

export const CATEGORIES = [
  {
    name: "All",
    label: "All Products",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Fruits & Vegetables",
    label: "Fresh Veg",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Dairy & Eggs",
    label: "Milk & Eggs",
    image:
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Atta, Rice & Dal",
    label: "Staples",
    image:
      "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Snacks & Biscuits",
    label: "Snacks",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Ice Creams",
    label: "Ice Creams",
    image:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Grocery Essentials",
    label: "Grocery",
    image:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Daily Needs",
    label: "Daily Needs",
    image:
      "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=300&q=80",
  },
  {
    name: "Mill Fresh Powders",
    label: "Mill Fresh",
    image: "/red-chilli-powder.png",
  },
];